/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GrntCarousel {
    }
}
declare global {
    interface HTMLGrntCarouselElement extends Components.GrntCarousel, HTMLStencilElement {
    }
    var HTMLGrntCarouselElement: {
        prototype: HTMLGrntCarouselElement;
        new (): HTMLGrntCarouselElement;
    };
    interface HTMLElementTagNameMap {
        "grnt-carousel": HTMLGrntCarouselElement;
    }
}
declare namespace LocalJSX {
    interface GrntCarousel {
    }
    interface IntrinsicElements {
        "grnt-carousel": GrntCarousel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "grnt-carousel": LocalJSX.GrntCarousel & JSXBase.HTMLAttributes<HTMLGrntCarouselElement>;
        }
    }
}
